"""
HIVE Learn Layer — tam ansiklopedi, rehber ve wizard içerikleri.

hive_academy, hive_mentor ve first_run_wizard tarafından import edilir.
"""

from __future__ import annotations

from typing import Any


def module_entry(
    module_id: str,
    title: str,
    *,
    purpose: str,
    what_it_does: str,
    when_to_use: str,
    when_not_to_use: str,
    inputs: list[str],
    outputs: list[str],
    related: list[str],
    example: str,
    common_mistakes: list[str],
    pro_tips: list[str],
    first_steps: list[str],
    category: str = "tools",
    icon: str = "📦",
    env_keys: list[str] | None = None,
    api_prefix: str = "",
    guide_id: str = "",
) -> dict[str, Any]:
    return {
        "module_id": module_id,
        "title": title,
        "purpose": purpose,
        "what_it_does": what_it_does,
        "when_to_use": when_to_use,
        "when_not_to_use": when_not_to_use,
        "inputs": inputs,
        "outputs": outputs,
        "related_modules": related,
        "example_usage": example,
        "common_mistakes": common_mistakes,
        "advanced_tips": pro_tips,
        "first_steps": first_steps,
        "category": category,
        "icon": icon,
        "env_keys": env_keys or [],
        "api_prefix": api_prefix,
        "guide_id": guide_id or f"guide_{module_id}",
    }


# ── Eksik / genişletilmiş modül ansiklopedisi ──────────────────────────────

EXTRA_ENCYCLOPEDIA: dict[str, dict[str, Any]] = {
    "action_orchestrator": module_entry(
        "action_orchestrator", "Action Orchestrator",
        category="command", icon="⚡",
        api_prefix="/api/action-orchestrator",
        purpose="Karar motorları ile yürütme katmanı arasında köprü — kararı aksiyona çevirir.",
        what_it_does="Mission Control, Agent, SERP, Opportunity ve Publisher'dan gelen önerileri kuyruklar; onay, erteleme ve tamamlama akışını yönetir.",
        when_to_use="Günlük görev listesinden hangi aksiyonun gerçekten çalıştırılacağını seçmek ve takip etmek için.",
        when_not_to_use="Ham keyword analizi — ilgili analiz modülüne gidin.",
        inputs=["Mission Control actions", "Agent missions", "Modül önerileri", "Brain events"],
        outputs=["Orchestration queue", "Execution status", "Completed action log"],
        related=["mission_control_center", "autonomous_seo_agent", "publisher_hub", "hive_brain_engine"],
        first_steps=[
            "Mission Control → Next Best Actions listesini inceleyin",
            "Action Orchestrator'da kuyruğu açın",
            "CRITICAL öncelikli aksiyonu onaylayın ve ilgili modüle gidin",
            "Tamamlandığında 'Done' işaretleyin — Brain'e event düşer",
        ],
        example="SERP Defense CRITICAL tehdit → Orchestrator'da ack → Content Refresh critical sayfaları işle → done.",
        common_mistakes=["Onaylamadan modüle gitmek (Brain'de iz kaybolur)", "Done işaretlemeden yeni göreve geçmek"],
        pro_tips=["Orchestrator panelini Mission Control'de sabit tutun", "Haftalık review için export alın"],
    ),
    "github_pages_worker": module_entry(
        "github_pages_worker", "GitHub Pages Worker",
        category="workers", icon="🐙",
        api_prefix="/api/github-pages",
        env_keys=["GITHUB_TOKEN"],
        guide_id="guide_github_pages",
        purpose="Statik support site'ları GitHub Pages üzerinden otomatik deploy eder.",
        what_it_does="Authority Mesh task'larını alır, repo oluşturur/günceller, GitHub Actions veya Pages ile yayınlar.",
        when_to_use="Authority Mesh planında GitHub Pages kanalı seçildiğinde; hızlı statik geo hub için.",
        when_not_to_use="WordPress money site içeriği — Publisher Hub / WordPress Manager.",
        inputs=["GITHUB_TOKEN", "Mesh task", "HTML/Markdown içerik", "Repo adı"],
        outputs=["Published Pages URL", "Repo link", "Deploy status"],
        related=["authority_mesh_engine", "astro_auto_publisher", "publisher_hub"],
        first_steps=[
            "backend/.env → GITHUB_TOKEN=ghp_... ekleyin",
            "Authority Mesh → GitHub Pages sekmesini açın",
            "Health endpoint provider_ready=true olmalı",
            "Mesh planından task kuyruğa alın ve publish edin",
        ],
        example="Kuşadası gece hayatı support hub → GitHub repo hive-kusadasi-hub → https://user.github.io/hive-kusadasi-hub/",
        common_mistakes=["Token'a repo scope vermemek", "Private repo + Pages ayarı eksik"],
        pro_tips=["Mission Control worker_status.github_pages kartını izleyin", "Token rotate edince wizard adım 2'yi yeniden doğrulayın"],
    ),
    "google_sites_worker": module_entry(
        "google_sites_worker", "Google Sites Worker",
        category="workers", icon="📄",
        api_prefix="/api/google-sites",
        env_keys=["GOOGLE_REFRESH_TOKEN", "Playwright profil"],
        guide_id="guide_google_sites",
        purpose="Google Sites üzerinde support/authority sayfalarını otomatik oluşturur ve günceller.",
        what_it_does="Playwright ile Google oturumu açar, Sites editöründe içerik yerleştirir, publish eder.",
        when_to_use="Authority Mesh'te Google Sites kanalı; hızlı trust signal için branded support page.",
        when_not_to_use="GitHub Pages yeterliyse — daha hafif worker.",
        inputs=["Google OAuth / Playwright session", "Mesh task içeriği", "Site başlığı"],
        outputs=["Google Sites URL", "Task status", "login_required flag"],
        related=["authority_mesh_engine", "support_network_engine", "publisher_hub"],
        first_steps=[
            "Playwright browser profilinde Google hesabına giriş yapın",
            "Authority Mesh → Google Sites sekmesi → provider_ready kontrol",
            "login_required_tasks=0 olana kadar tarayıcı oturumunu doğrulayın",
            "İlk mesh task oluşturup publish edin",
        ],
        example="Support site: 'Kuşadası Gece Rehberi' → Google Sites URL → money site'e contextual link.",
        common_mistakes=["Login required uyarısını görmezden gelmek", "CAPTCHA oturumunu manuel tamamlamamak"],
        pro_tips=["Mission Control'de login_required alert gelince hemen müdahale edin", "Her geo vertical için ayrı site şablonu kullanın"],
    ),
    "seo_quality_gate": module_entry(
        "seo_quality_gate", "SEO Quality Gate",
        category="tools", icon="🔬",
        api_prefix="/api/seo-quality-gate",
        purpose="Yayın öncesi içerik kalite ve SEO uyumluluk kontrolü.",
        what_it_does="Thin content, keyword stuffing, meta eksikliği, internal link ve schema kontrollerini skorlar.",
        when_to_use="Publisher kuyruğundan yayın öncesi; Astro deploy öncesi; CRE refresh sonrası.",
        when_not_to_use="Keyword araştırması aşamasında — Opportunity Engine.",
        inputs=["HTML/Markdown içerik", "Target keyword", "Meta fields"],
        outputs=["Pass/fail", "Quality score", "Issue list"],
        related=["publisher_hub", "astro_auto_publisher", "content_refresh_engine"],
        first_steps=[
            "Publisher'dan draft seçin veya içeriği yapıştırın",
            "Quality Gate → Scan çalıştırın",
            "CRITICAL issue varsa düzeltin, tekrar tarayın",
            "Pass sonrası publish/deploy",
        ],
        example="7 kuyruk içeriği → Gate fail 2 → meta description ekle → pass → WP publish.",
        common_mistakes=["Fail içeriği zorla yayınlamak", "Gate skorunu SERP Defense ile karıştırmak"],
        pro_tips=["Mission Control quality_gate_health düşükse kuyruk taraması yapın"],
    ),
    "tumblr": module_entry(
        "tumblr", "Tumblr Yöneticisi",
        category="workers", icon="📝",
        api_prefix="/api/tumblr",
        env_keys=["TUMBLR_CONSUMER_KEY", "TUMBLR_CONSUMER_SECRET"],
        purpose="Tumblr OAuth ve micro-content yayın kanalı.",
        what_it_does="OAuth oturumu, blog seçimi, kısa içerik ve link post yayını.",
        when_to_use="Support network çeşitliliği; hızlı social signal; cross-post pipeline.",
        when_not_to_use="Uzun form SEO içeriği — WordPress veya Astro.",
        inputs=["Tumblr OAuth", "Blog seçimi", "Post içeriği"],
        outputs=["Published post URL", "OAuth session"],
        related=["publisher_hub", "support_network_engine"],
        first_steps=[
            "Tumblr Developer'da app oluşturun",
            ".env consumer key/secret ekleyin",
            "Panel → Tumblr → OAuth bağlantısı",
            "Publisher'dan Tumblr kanalına cross-post",
        ],
        example="FAQ özeti Tumblr post → support link → money site internal link graph güçlenir.",
        common_mistakes=["OAuth callback URL yanlış (localhost:4000 olmalı)", "Default blog seçmeden publish"],
        pro_tips=["First Run Wizard Blogger adımından sonra Tumblr opsiyonel ekleyin"],
    ),
    "network_replicator": module_entry(
        "network_replicator", "Network Replicator",
        category="network", icon="🧬",
        api_prefix="/api/network-replicator",
        purpose="Başarılı site ağını yeni geo/vertical'a klonlama planı.",
        what_it_does="Mevcut network topolojisini analiz eder, replikasyon blueprint üretir.",
        when_to_use="Bir vertical'da çalışan ağı başka şehir/niche'e ölçeklerken.",
        when_not_to_use="İlk site kurulumu — First Run Wizard + Astro Factory.",
        inputs=["Kaynak network ID", "Hedef geo/keyword", "Domain stratejisi"],
        outputs=["Replication plan", "Site listesi", "Link map"],
        related=["site_replicator", "authority_mesh_engine", "support_network_engine"],
        first_steps=[
            "Support Network'te kaynak ağı seçin",
            "Network Replicator → yeni hedef geo tanımlayın",
            "Blueprint'i Authority Mesh task'larına dönüştürün",
        ],
        example="Kuşadası network → Bodrum replikasyon → 4 yeni support site task.",
        common_mistakes=["Link anchor çeşitliliğini kopyalamadan birebir klon"],
        pro_tips=["Academy workflow: Network Büyütme haritasını takip edin"],
    ),
    "site_replicator": module_entry(
        "site_replicator", "Site Replicator",
        category="network", icon="📋",
        api_prefix="/api/site-replicator",
        purpose="Tek site şablonunu yeni domain/geo'ya kopyalar.",
        what_it_does="Template, içerik yapısı ve SEO ayarlarını yeni site instance'ına aktarır.",
        when_to_use="Aynı yapıda çoklu geo landing; Astro/WP template çoğaltma.",
        when_not_to_use="Tamamen farklı niche — sıfırdan Astro Factory.",
        inputs=["Kaynak site URL/ID", "Hedef domain", "Geo parametreleri"],
        outputs=["Yeni site instance", "Deploy checklist"],
        related=["astro_factory", "network_replicator", "authority_mesh_engine"],
        first_steps=[
            "Kaynak siteyi Rank Watcher'da doğrulayın",
            "Site Replicator'da hedef domain girin",
            "Factory veya WP'de clone deploy edin",
        ],
        example="balkutusu.com/kusadasi şablonu → balkutusu.com/bodrum clone.",
        common_mistakes=["Canonical ve hreflang ayarlarını unutmak"],
        pro_tips=["Clone sonrası Crawl Gap ile duplicate content kontrolü"],
    ),
    "hive_academy": module_entry(
        "hive_academy", "HIVE Academy",
        category="learn", icon="🎓",
        api_prefix="/api/hive-academy",
        purpose="HIVE SEO OS modül ansiklopedisi ve operasyon rehberleri.",
        what_it_does="Her modülün amacını, workflow haritalarını, rehberleri ve kavram sözlüğünü sunar.",
        when_to_use="Yeni modül öğrenirken; ekip onboarding; workflow planlarken.",
        when_not_to_use="Canlı operasyon — Mission Control.",
        inputs=["Modül listesi", "Kullanıcı ilerleme state"],
        outputs=["Ansiklopedi", "Workflow adımları", "Tam rehber içeriği"],
        related=["hive_mentor", "first_run_wizard", "mission_control_center"],
        first_steps=["Modül Ansiklopedisi sekmesinden başlayın", "Workflow haritası seçin", "Rehberler sekmesinde adım adım okuyun"],
        example="Publisher Hub rehberini oku → workflow Content Publishing takip et → modüle git.",
        common_mistakes=["Sadece başlık okuyup first_steps atlamak"],
        pro_tips=["Export ile PDF/JSON backup alın", "Her yeni modülde ansiklopedi kaydını viewed işaretleyin"],
    ),
    "hive_mentor": module_entry(
        "hive_mentor", "HIVE Mentor",
        category="learn", icon="🧭",
        api_prefix="/api/hive-mentor",
        purpose="Doğal dil ile modül yönlendirme — hangi modüle gitmeliyim?",
        what_it_does="Intent eşleştirme ile modül sırası, gerekçe ve workflow linki üretir.",
        when_to_use="Hedefinizi biliyorsunuz ama hangi modül sırası gerektiğini bilmiyorsunuz.",
        when_not_to_use="Derin teknik analiz — doğrudan ilgili engine.",
        inputs=["Kullanıcı sorusu", "Intent kuralları"],
        outputs=["Modül adımları", "Özet", "Workflow ID"],
        related=["hive_academy", "mission_control_center", "first_run_wizard"],
        first_steps=["Örnek sorulardan birini tıklayın veya hedefinizi yazın", "Adım kartlarından modüle gidin", "Academy workflow ile derinleşin"],
        example="'Google Sites nasıl açılır' → Authority Mesh → Google Sites sekmesi.",
        common_mistakes=["Çok genel soru sormak — geo/keyword belirtin"],
        pro_tips=["Intent kataloğunu inceleyin", "SERP savunması için 'tehdit' kelimesini kullanın"],
    ),
    "first_run_wizard": module_entry(
        "first_run_wizard", "First Run Wizard",
        category="learn", icon="🚀",
        api_prefix="/api/first-run",
        purpose="8 adımlı HIVE OS ilk kurulum ve bağlantı checklist'i.",
        what_it_does="WP, GitHub, Blogger, Astro, Mesh, Publish, Rank, Mission Control durumlarını gerçek API ile kontrol eder.",
        when_to_use="İlk kez HIVE kurulumu; yeni ekip üyesi onboarding; bağlantı kopması sonrası.",
        when_not_to_use="Günlük operasyon — Mission Control.",
        inputs=["Modül health endpoint'leri", "OAuth session'ları", ".env key'leri"],
        outputs=["Adım durumu", "connect_required flag", "İlerleme yüzdesi"],
        related=["wordpress", "authority_mesh_engine", "publisher_hub", "rank_index_watcher"],
        first_steps=["Adım 1 WordPress bağlantısından başlayın", "Her adımda 'Kontrol' ile otomatik doğrulama", "connect_required görürseniz .env ve OAuth tamamlayın"],
        example="0% → WP bağlandı 12% → GitHub token 25% → ... → Mission Control 100%.",
        common_mistakes=["Manuel 'Tamamladım' ile gerçek bağlantıyı karıştırmak"],
        pro_tips=["Her adımın detay panelinde env checklist var", "Academy rehber linklerini kullanın"],
    ),
}


GUIDE_DETAILS: dict[str, dict[str, Any]] = {
    "guide_publisher": {
        "guide_id": "guide_publisher",
        "title": "Publisher Hub — Tam Operasyon Rehberi",
        "module_id": "publisher_hub",
        "summary": "Taslaktan canlı yayına: kuyruk, kalite kapısı ve çoklu kanal dağıtımı.",
        "estimated_time": "30-45 dk",
        "prerequisites": ["WordPress veya Blogger bağlantısı (Wizard adım 1-3)", "En az 1 hazır içerik veya CRE export"],
        "steps": [
            {"order": 1, "title": "Publisher Hub dashboard aç", "body": "Sidebar → Publisher Hub. Queued, Drafts, Published sayaçlarını not edin. Boş kuyruk = fırsat kaçırılıyor."},
            {"order": 2, "title": "İçerik kaynağı seç", "body": "CRE refresh export, QIE FAQ cluster, Astro Factory çıktısı veya manuel draft. Her kaynak farklı metadata taşır."},
            {"order": 3, "title": "Kuyruğa al", "body": "Draft oluştur → target keyword + channel seç → queue. SEO Quality Gate otomatik tetiklenebilir."},
            {"order": 4, "title": "Quality Gate", "body": "Fail varsa meta, heading ve internal link düzelt. Pass olmadan publish etmeyin — Brain'de quality_failed event oluşur."},
            {"order": 5, "title": "Kanal yayını", "body": "WordPress: site seç + publish. Blogger: default blog. Tumblr: OAuth sonrası cross-post."},
            {"order": 6, "title": "Doğrulama", "body": "Brain timeline'da publish event. Rank Watcher'a URL ekle. Mission Control publisher_status güncellenmeli."},
        ],
        "checklist": ["Kanal connected", "Draft metadata dolu", "Quality Gate pass", "Published URL canlı", "Brain event kaydı"],
        "troubleshooting": [
            {"issue": "Publish failed", "fix": "Kanal credentials kontrol — Wizard WP/Blogger adımları"},
            {"issue": "Queue stuck", "fix": "seo_quality_gate health + failed count Mission Control'de"},
        ],
    },
    "guide_serp_defense": {
        "guide_id": "guide_serp_defense",
        "title": "SERP Defense — Fortress Savunma Rehberi",
        "module_id": "serp_defense_engine",
        "summary": "Keyword pozisyonunu koruma: fortress analizi, tehdit tespiti, savunma planı.",
        "estimated_time": "20-40 dk",
        "prerequisites": ["Rank Watcher projesi", "Hedef keyword listesi"],
        "steps": [
            {"order": 1, "title": "Rank alert kontrol", "body": "Rank Watcher'da rank_drop alert var mı? Mission Control Active Threats ile cross-check."},
            {"order": 2, "title": "Fortress analizi", "body": "SERP Defense → keyword gir → Fortress Score (0-100). <50 = CRITICAL savunma gerekli."},
            {"order": 3, "title": "Top risks", "body": "Pressure level CRITICAL olan keyword'leri listeleyin. Rakip URL ve snippet değişimlerini inceleyin."},
            {"order": 4, "title": "Content Refresh", "body": "Savunma keyword'üne bağlı sayfaları CRE'de critical olarak işaretleyin."},
            {"order": 5, "title": "Agent mission", "body": "Autonomous Agent daily mission'da SERP savunma görevini tamamlayın."},
        ],
        "checklist": ["Fortress skoru kayıtlı", "Critical tehdit listesi", "Refresh planı", "Internal link güncellemesi"],
        "troubleshooting": [
            {"issue": "Fortress düşük ama rank stabil", "fix": "SERP snapshot gecikmesi — 24 saat sonra tekrar tara"},
            {"issue": "Pressure CRITICAL", "fix": "Content Refresh + Authority Mesh destek linki acil"},
        ],
    },
    "guide_opportunity": {
        "guide_id": "guide_opportunity",
        "title": "Opportunity Engine — Quick Win Rehberi",
        "module_id": "opportunity_engine",
        "summary": "Büyüme fırsatlarını skorla, quick win seç, içerik planına dönüştür.",
        "estimated_time": "25 dk",
        "prerequisites": ["Keyword seed listesi veya Crawl Gap export"],
        "steps": [
            {"order": 1, "title": "Dashboard tara", "body": "Opportunity Engine aç → top_opportunities listesi. opportunity_score > 75 = quick win adayı."},
            {"order": 2, "title": "Filtrele", "body": "Düşük zorluk + yüksek trafik potansiyeli. Geo keyword'lerinizi önceliklendirin."},
            {"order": 3, "title": "Crawl Gap cross-ref", "body": "Aynı keyword için FAQ/entity gap var mı? Varsa tek içerik paketi planlayın."},
            {"order": 4, "title": "QIE FAQ", "body": "People Also Ask sorularını QIE ile cluster'a dönüştürün."},
            {"order": 5, "title": "Publisher pipeline", "body": "Seçilen 3 quick win'i draft → queue → publish."},
        ],
        "checklist": ["Min 3 quick win seçildi", "Gap analizi yapıldı", "FAQ cluster hazır", "Publish kuyruğunda"],
        "troubleshooting": [
            {"issue": "Opportunity boş", "fix": "Crawl Gap analyze-domain çalıştırın"},
            {"issue": "Skor düşük", "fix": "Rank Watcher verisi ekleyin — pozisyon sinyali skoru artırır"},
        ],
    },
    "guide_crawl_gap": {
        "guide_id": "guide_crawl_gap",
        "title": "Crawl & Gap — İçerik Boşluk Rehberi",
        "module_id": "crawl_gap_engine",
        "summary": "Site crawl sonrası FAQ, entity ve cluster açıklarını kapatma.",
        "estimated_time": "40-60 dk",
        "prerequisites": ["Site URL", "Proje ID"],
        "steps": [
            {"order": 1, "title": "Domain analizi", "body": "analyze-domain ile crawl başlat. Job bitene kadar bekleyin — ara sonuçlara güvenmeyin."},
            {"order": 2, "title": "Gap raporu", "body": "critical_gaps, faq_gaps, entity_gaps sayılarına bakın."},
            {"order": 3, "title": "Cluster üret", "body": "Generate Cluster ile FAQ grupları oluşturun."},
            {"order": 4, "title": "Opportunity export", "body": "Gap verisini Opportunity Engine'e aktarın."},
            {"order": 5, "title": "Publisher", "body": "En yüksek gap skorlu cluster'ı yayınlayın."},
        ],
        "checklist": ["Crawl tamamlandı", "Critical gap listesi", "Cluster oluşturuldu", "Export alındı"],
        "troubleshooting": [
            {"issue": "Crawl timeout", "fix": "robots.txt ve rate limit kontrol"},
            {"issue": "0 gap", "fix": "Competitor compare-domain ile benchmark"},
        ],
    },
    "guide_rank_watcher": {
        "guide_id": "guide_rank_watcher",
        "title": "Rank Watcher — İlk Proje Rehberi",
        "module_id": "rank_index_watcher",
        "summary": "Keyword pozisyon ve index sağlığı takibi kurulumu.",
        "estimated_time": "15 dk",
        "prerequisites": ["Domain", "Keyword listesi"],
        "steps": [
            {"order": 1, "title": "Proje oluştur", "body": "Rank Watcher → New Project → domain + isim."},
            {"order": 2, "title": "Keyword ekle", "body": "Money keyword + long-tail varyantlar. Min 5 keyword önerilir."},
            {"order": 3, "title": "Alert ayarları", "body": "rank_drop ve index_issue alert'leri açık olsun."},
            {"order": 4, "title": "Mission Control", "body": "rank_status kartında proje görünmeli."},
            {"order": 5, "title": "Deploy sonrası", "body": "Yeni URL publish sonrası 48 saat içinde index kontrol."},
        ],
        "checklist": ["Proje oluştu", "5+ keyword", "Alert aktif", "Mission Control entegrasyonu"],
        "troubleshooting": [
            {"issue": "project_count 0", "fix": "Proje kaydet ve refresh — Brain backfill opsiyonel"},
        ],
    },
    "guide_authority_mesh": {
        "guide_id": "guide_authority_mesh",
        "title": "Authority Mesh — Support Site Ağı Rehberi",
        "module_id": "authority_mesh_engine",
        "summary": "Google Sites + GitHub Pages ile authority dağıtım ağı kurulumu.",
        "estimated_time": "45-90 dk",
        "prerequisites": ["GITHUB_TOKEN", "Google Playwright oturumu", "Money site URL"],
        "steps": [
            {"order": 1, "title": "Mesh plan", "body": "Keyword + money site URL → create mesh plan. Support site rolleri atanır."},
            {"order": 2, "title": "Worker health", "body": "GitHub Pages + Google Sites sekmelerinde provider_ready=true."},
            {"order": 3, "title": "Task kuyruğu", "body": "Plan'dan task oluştur — queued_tasks artmalı."},
            {"order": 4, "title": "Publish", "body": "Worker task'ları işle — login_required varsa tarayıcı oturumu aç."},
            {"order": 5, "title": "Network skor", "body": "Support Network overall_network_score kontrol."},
        ],
        "checklist": ["Mesh plan var", "Workers ready", "Min 1 published support site", "Link policy uygulandı"],
        "troubleshooting": [
            {"issue": "login_required_tasks > 0", "fix": "Google Sites Playwright profilinde oturum aç"},
            {"issue": "provider_missing GitHub", "fix": "GITHUB_TOKEN .env + Wizard adım 2"},
        ],
    },
    "guide_wordpress": {
        "guide_id": "guide_wordpress",
        "title": "WordPress — İlk Bağlantı Rehberi",
        "module_id": "wordpress",
        "summary": "REST API Application Password ile güvenli WP oturumu.",
        "estimated_time": "10-15 dk",
        "prerequisites": ["WP admin erişimi", "Application Passwords eklentisi/özelliği"],
        "steps": [
            {"order": 1, "title": "Application Password", "body": "WP Admin → Users → Application Passwords → 'HIVE Panel' oluştur."},
            {"order": 2, "title": "Panel bağlantısı", "body": "WordPress Manager → site URL + username + app password."},
            {"order": 3, "title": "Site listesi", "body": "Multisite ise alt siteler görünmeli."},
            {"order": 4, "title": "Publisher kanalı", "body": "Publisher Hub'da WP kanalı connected."},
            {"order": 5, "title": "Wizard", "body": "First Run adım 1 otomatik tamamlanır."},
        ],
        "checklist": ["Session dosyası oluştu", "Site listesi geldi", "Test publish OK"],
        "troubleshooting": [
            {"issue": "401 Unauthorized", "fix": "Application password yenile — admin şifresi kullanma"},
            {"issue": "REST API kapalı", "fix": "Permalink + REST endpoint kontrol"},
        ],
    },
    "guide_github_pages": {
        "guide_id": "guide_github_pages",
        "title": "GitHub Pages Worker Rehberi",
        "module_id": "github_pages_worker",
        "summary": "Token yapılandırması ve ilk Pages deploy.",
        "estimated_time": "15 dk",
        "prerequisites": ["GitHub hesabı", "repo oluşturma yetkisi"],
        "steps": [
            {"order": 1, "title": "Token", "body": "GitHub Settings → Developer → PAT → repo scope. .env GITHUB_TOKEN="},
            {"order": 2, "title": "Health", "body": "GET /api/github-pages/health → provider_ready: true"},
            {"order": 3, "title": "Authority Mesh", "body": "GitHub Pages sekmesinden task oluştur"},
            {"order": 4, "title": "Deploy", "body": "Task publish → Pages URL Mission Control worker_status'ta"},
        ],
        "checklist": ["Token geçerli", "provider_ready", "İlk URL live"],
        "troubleshooting": [
            {"issue": "provider_missing", "fix": "Token scope ve .env restart"},
        ],
    },
    "guide_google_sites": {
        "guide_id": "guide_google_sites",
        "title": "Google Sites Worker Rehberi",
        "module_id": "google_sites_worker",
        "summary": "Playwright oturumu ve ilk Google Sites publish.",
        "estimated_time": "20-30 dk",
        "prerequisites": ["Google hesabı", "Playwright browser profil"],
        "steps": [
            {"order": 1, "title": "Playwright login", "body": "Authority Mesh → Google Sites → 'Open Browser' ile Google oturumu açın."},
            {"order": 2, "title": "Health check", "body": "login_required_count=0 olmalı."},
            {"order": 3, "title": "Mesh task", "body": "Support site içeriği ile task oluşturun."},
            {"order": 4, "title": "Publish", "body": "Worker task işle — Google Sites URL Brain'e düşer."},
        ],
        "checklist": ["Google oturum açık", "login_required=0", "İlk site URL"],
        "troubleshooting": [
            {"issue": "login_required", "fix": "Manuel tarayıcı oturumu — CAPTCHA tamamla"},
        ],
    },
    "guide_getting_started": {
        "guide_id": "guide_getting_started",
        "title": "HIVE SEO OS — Başlangıç Rehberi",
        "module_id": "first_run_wizard",
        "summary": "8 adımlı wizard ile sıfırdan operasyonel HIVE kurulumu.",
        "estimated_time": "2-4 saat",
        "prerequisites": ["backend/.env yapılandırılmış", "Panel http://localhost:4000 erişilebilir"],
        "steps": [
            {"order": 1, "title": "First Run Wizard aç", "body": "Sidebar LEARN → First Run Wizard. İlerleme çubuğu 0%'dan başlar."},
            {"order": 2, "title": "Bağlantılar (1-3)", "body": "WordPress, GitHub, Blogger — her adımda Kontrol butonu ile otomatik doğrulama."},
            {"order": 3, "title": "İçerik altyapısı (4-6)", "body": "Astro proje, Authority Mesh, ilk publish."},
            {"order": 4, "title": "İzleme (7-8)", "body": "Rank Watcher projesi + Mission Control aktivasyonu."},
            {"order": 5, "title": "Günlük rutin", "body": "Mission Control → Agent → Orchestrator döngüsü."},
        ],
        "checklist": ["8/8 adım tamam", "Mission Control health OK", "Brain'de event var"],
        "troubleshooting": [
            {"issue": "Adım otomatik tamamlanmıyor", "fix": "Modül health endpoint + .env key kontrol"},
        ],
    },
}


EXTRA_GLOSSARY: dict[str, str] = {
    "connect_required": "Wizard veya modül health'inde bağlantı/kimlik bilgisi eksik. .env veya OAuth tamamlanmalı.",
    "provider_ready": "Worker (GitHub/Google Sites) token veya oturum hazır — task kuyruğu işlenebilir.",
    "login_required": "Google Sites worker tarayıcı oturumu gerektiriyor — Playwright profilde giriş yapın.",
    "fortress_score": "Keyword SERP savunma gücü 0-100. 70+ güvenli, 50 altı acil müdahale.",
    "opportunity_score": "Büyüme potansiyeli; trafik tahmini + zorluk + mevcut pozisyon.",
    "mesh_plan": "Authority Mesh'te support site rol, link anchor ve dağıtım planı.",
    "quality_gate": "Yayın öncesi SEO/kalite kontrol katmanı — fail içerik yayınlanmamalı.",
    "brain_backfill": "Eski activity log ve engine state'lerden Brain hafızasını doldurma.",
    "orchestrator_queue": "Onay bekleyen veya yürütülen aksiyonların Action Orchestrator kuyruğu.",
    "geo_vertical": "Şehir/niche odaklı SEO vertical — örn. Kuşadası gece hayatı.",
    "support_site": "Money site'e link equity sağlayan otorite/destek sitesi.",
    "money_site": "Ana gelir/hedef domain — en yüksek öncelikli koruma ve optimizasyon.",
}


MENTOR_EXTRA_RULES: list[dict[str, Any]] = [
    {
        "intent": "google_sites_setup",
        "keywords": ["google sites", "sites ac", "sites aç", "sites nasil", "sites nasıl", "playwright", "google site"],
        "steps": [
            {"order": 1, "module_id": "authority_mesh_engine", "title": "Authority Mesh", "reason": "Google Sites sekmesi — mesh plan ve worker yönetimi", "mesh_tab": "google_sites"},
            {"order": 2, "module_id": "first_run_wizard", "title": "First Run Wizard", "reason": "GitHub + Google worker bağlantı durumu"},
            {"order": 3, "module_id": "hive_academy", "title": "HIVE Academy", "reason": "guide_google_sites tam adım adım rehber"},
        ],
        "workflow_id": "authority_building",
        "tips": ["Playwright profilde Google oturumu açık olmalı", "login_required_count=0 olana kadar bekleyin"],
    },
    {
        "intent": "wordpress_setup",
        "keywords": ["wordpress", "wp bagla", "wp bağla", "wp kur", "application password"],
        "steps": [
            {"order": 1, "module_id": "wordpress", "title": "WordPress Manager", "reason": "REST API Application Password oturumu"},
            {"order": 2, "module_id": "first_run_wizard", "title": "First Run Wizard", "reason": "Adım 1 otomatik doğrulama"},
            {"order": 3, "module_id": "publisher_hub", "title": "Publisher Hub", "reason": "WP kanalı ile ilk yayın"},
        ],
        "workflow_id": "content_publishing",
        "tips": ["Admin şifresi değil Application Password kullanın", "Multisite ise doğru subsite seçin"],
    },
    {
        "intent": "github_pages_setup",
        "keywords": ["github", "github pages", "token", "ghp_", "repo"],
        "steps": [
            {"order": 1, "module_id": "authority_mesh_engine", "title": "Authority Mesh", "reason": "GitHub Pages sekmesi — token health", "mesh_tab": "github_pages"},
            {"order": 2, "module_id": "first_run_wizard", "title": "First Run Wizard", "reason": "Adım 2 GitHub bağlantısı"},
            {"order": 3, "module_id": "hive_academy", "title": "HIVE Academy", "reason": "guide_github_pages rehberi"},
        ],
        "workflow_id": "authority_building",
        "tips": ["GITHUB_TOKEN .env'de repo scope ile tanımlı olmalı"],
    },
    {
        "intent": "refresh_content",
        "keywords": ["refresh", "yenile", "decay", "eski içerik", "güncelle", "guncelle"],
        "steps": [
            {"order": 1, "module_id": "content_refresh_engine", "title": "Content Refresh", "reason": "Critical/high priority decay sayfaları"},
            {"order": 2, "module_id": "seo_quality_gate", "title": "SEO Quality Gate", "reason": "Yenilenen içerik kalite kontrolü"},
            {"order": 3, "module_id": "publisher_hub", "title": "Publisher Hub", "reason": "Güncellenmiş içeriği yeniden yayınla"},
        ],
        "workflow_id": "serp_defense",
        "tips": ["SERP Defense risk keyword'leri ile cross-reference yapın"],
    },
    {
        "intent": "success_path",
        "keywords": ["ne yapmaliyim", "ne yapmalıyım", "what should i do", "success path", "basari yolu", "başarı yolu", "onboarding", "aktivasyon", "activation"],
        "steps": [
            {"order": 1, "module_id": "hive_success_path", "title": "Success Path", "reason": "Aktivasyon skoru ve sıradaki adım"},
            {"order": 2, "module_id": "first_run_wizard", "title": "First Run Wizard", "reason": "Kurulum tamamlanmadıysa önce wizard"},
            {"order": 3, "module_id": "hive_academy", "title": "HIVE Academy", "reason": "Eksik adım için ilgili ders"},
        ],
        "workflow_id": None,
        "tips": ["Success Path %100 hedefi — ilk lead'e kadar rehberlik", "Her adım otomatik algılanır"],
    },
    {
        "intent": "mission_control_help",
        "keywords": ["mission control", "command center", "kokpit", "dashboard", "operasyon"],
        "steps": [
            {"order": 1, "module_id": "mission_control_center", "title": "Mission Control", "reason": "Günlük operasyon özeti ve sistem sağlığı"},
            {"order": 2, "module_id": "action_orchestrator", "title": "Action Orchestrator", "reason": "Önerilen aksiyonları yürüt"},
            {"order": 3, "module_id": "hive_brain_engine", "title": "HIVE Brain", "reason": "Son event timeline"},
        ],
        "workflow_id": None,
        "tips": ["Her sabah Mission Control ile başlayın", "source_status not_configured modülleri Wizard'dan tamamlayın"],
    },
    {
        "intent": "brain_memory",
        "keywords": ["brain", "hafıza", "memory", "timeline", "geçmiş", "gecmis", "log", "event"],
        "steps": [
            {"order": 1, "module_id": "hive_brain_engine", "title": "HIVE Brain", "reason": "Event timeline ve proje hafızası"},
            {"order": 2, "module_id": "hive_brain_engine", "title": "Backfill", "reason": "Log Backfill ile eski kayıtları içe aktarın"},
            {"order": 3, "module_id": "mission_control_center", "title": "Mission Control", "reason": "Live Event Stream doğrulama"},
        ],
        "workflow_id": None,
        "tips": ["project_id tutarlı kullanın", "Backfill sonrası dashboard empty state kalkar"],
    },
]


WIZARD_STEP_DETAILS: dict[str, dict[str, Any]] = {
    "wordpress": {
        "instructions": [
            "WordPress Admin → Kullanıcılar → Profil → Application Passwords bölümüne gidin",
            "'HIVE Panel' adıyla yeni password oluşturun — gösterilen şifreyi kopyalayın",
            "HIVE Panel → WordPress Manager → Site URL + kullanıcı adı + application password girin",
            "'Bağlan' tıklayın — site listesi gelmeli",
        ],
        "env_vars": [
            {"key": "WP_URL", "description": "WordPress site URL (https://example.com)"},
            {"key": "WP_USERNAME", "description": "WP kullanıcı adı (application password sahibi)"},
        ],
        "success_criteria": "ensure_wp_connected() true veya session dosyası mevcut",
        "troubleshooting": [
            "401 hatası → Application Password yenileyin",
            "REST API 404 → Permalink ayarlarını yeniden kaydedin",
        ],
    },
    "github": {
        "instructions": [
            "GitHub → Settings → Developer settings → Personal access tokens",
            "repo scope ile token oluşturun",
            "backend/.env → GITHUB_TOKEN=ghp_... ekleyin",
            "Backend restart → Authority Mesh GitHub Pages sekmesi → provider_ready kontrol",
        ],
        "env_vars": [{"key": "GITHUB_TOKEN", "description": "GitHub PAT — repo + pages yetkisi"}],
        "success_criteria": "github_pages_worker health provider_ready=true",
        "troubleshooting": ["provider_missing → token scope ve .env restart"],
    },
    "blogger": {
        "instructions": [
            "Google Cloud Console'da OAuth client oluşturun",
            "GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REFRESH_TOKEN .env'e ekleyin",
            "Panel → Blogger → OAuth akışını tamamlayın",
            "Default blog seçin",
        ],
        "env_vars": [
            {"key": "GOOGLE_CLIENT_ID", "description": "OAuth client ID"},
            {"key": "GOOGLE_CLIENT_SECRET", "description": "OAuth client secret"},
            {"key": "GOOGLE_REFRESH_TOKEN", "description": "Offline refresh token"},
        ],
        "success_criteria": "blogger_api get_status connected=true",
        "troubleshooting": ["Refresh token expired → OAuth yeniden"],
    },
    "astro_project": {
        "instructions": [
            "Astro Factory → yeni proje oluştur (template + domain + geo)",
            "Build alın — hata yoksa Auto Publisher'a aktarın",
            "Auto Publisher dashboard'da project_count >= 1 olmalı",
        ],
        "env_vars": [],
        "success_criteria": "astro_auto_publisher project_count > 0 veya astro_factory has_projects",
        "troubleshooting": ["Build fail → Factory log + template path kontrol"],
    },
    "authority_mesh": {
        "instructions": [
            "Authority Mesh → mesh plan oluştur (keyword + money site)",
            "Google Sites ve/veya GitHub worker'ları ready olmalı",
            "En az 1 task publish edin veya kuyruğa alın",
        ],
        "env_vars": [{"key": "GITHUB_TOKEN", "description": "GitHub Pages için gerekli"}],
        "success_criteria": "published_count > 0 veya queued_tasks > 0",
        "troubleshooting": ["login_required → Google oturum aç", "0 task → mesh plan oluştur"],
    },
    "first_publish": {
        "instructions": [
            "Publisher Hub → draft veya CRE export ile içerik oluştur",
            "SEO Quality Gate pass alın",
            "WordPress/Blogger kanalından publish edin",
            "published_count >= 1 olmalı",
        ],
        "env_vars": [],
        "success_criteria": "publisher_hub health published_count > 0",
        "troubleshooting": ["Publish fail → kanal credentials Wizard adım 1-3"],
    },
    "rank_watcher": {
        "instructions": [
            "Rank Watcher → New Project → domain girin",
            "Min 5 keyword ekleyin",
            "Alert ayarlarını açık bırakın",
            "Mission Control rank_status'ta proje görünmeli",
        ],
        "env_vars": [],
        "success_criteria": "rank_index_watcher health project_count > 0",
        "troubleshooting": ["project_count 0 → proje kaydet + refresh"],
    },
    "mission_control": {
        "instructions": [
            "Mission Control / Command Center sayfasını açın",
            "Dashboard yüklenmeli — system_health skoru görünmeli",
            "En az bir refresh sonrası last_opened_at kaydı oluşur",
        ],
        "env_vars": [{"key": "HIVE_API_KEY", "description": "Panel ↔ backend API key eşleşmesi"}],
        "success_criteria": "mission_control_center last_opened_at set",
        "troubleshooting": ["404 → backend restart scripts/stop-hive.sh && start-hive.sh"],
    },
}


SUCCESS_PATH_STEP_DETAILS: dict[str, dict[str, Any]] = {
    "provider_setup": {
        "instructions": [
            "Provider Control Center → Check All",
            "GitHub Pages, WordPress, Blogger, Cloudflare, Google Sites en az 2'si connected olmalı",
            "Eksik provider için Wizard adımlarına bakın",
        ],
        "success_criteria": "provider_control_center connected >= 2 (github, wordpress, blogger, cloudflare, google_sites)",
        "troubleshooting": ["not_configured → .env token + restart", "warning → Check Provider tekrar"],
    },
    "first_project": {
        "instructions": [
            "Campaign Engine → Create Campaign veya Astro Factory → yeni proje",
            "Domain + keyword tanımlayın",
            "Proje kaydı dashboard'da görünmeli",
        ],
        "success_criteria": "campaigns_total > 0 veya astro project_count > 0",
        "troubleshooting": ["Campaign fail → blueprint + keyword kontrol"],
    },
    "first_keyword": {
        "instructions": [
            "Rank Watcher → New Project → domain",
            "En az 1 keyword ekleyin ve track başlatın",
            "Keyword listesi projede görünmeli",
        ],
        "success_criteria": "rank_index_watcher projects keywords.length > 0",
        "troubleshooting": ["Keyword eklenmiyor → proje kaydet + refresh"],
    },
    "first_campaign": {
        "instructions": [
            "Campaign Engine → Create Campaign",
            "Goal seçin (ranking / authority / citation / lead)",
            "Generate Plan → en az 1 task oluşsun",
        ],
        "success_criteria": "campaign_engine campaigns_total > 0",
        "troubleshooting": ["Plan boş → keyword + domain doldurun"],
    },
    "first_authority": {
        "instructions": [
            "Authority Factory → Create Batch",
            "Provider seçin (Google Sites / GitHub / Blogger)",
            "Batch kuyruğa alın veya tamamlayın",
        ],
        "success_criteria": "authority_factory batches_count > 0",
        "troubleshooting": ["login_required → worker oturum aç", "0 batch → mesh plan oluştur"],
    },
    "first_publisher": {
        "instructions": [
            "Publisher Hub → draft oluştur veya CRE'den içerik al",
            "SEO Quality Gate geçin",
            "WordPress/Blogger kanalından publish edin",
        ],
        "success_criteria": "publisher_hub published_count > 0",
        "troubleshooting": ["Publish fail → kanal credentials Provider Setup"],
    },
    "first_citation": {
        "instructions": [
            "Citation Engine → Add Page veya Scan",
            "En az 1 sayfa citation analizi çalıştırın",
            "Citation score dashboard'da görünmeli",
        ],
        "success_criteria": "citation_engine pages_tracked > 0",
        "troubleshooting": ["0 page → URL ekle + analyze tetikle"],
    },
    "first_lead": {
        "instructions": [
            "Revenue Lead Engine → Track Lead veya form entegrasyonu",
            "İlk lead kaydı funnel'da görünmeli",
            "Mission Control revenue_status today_leads >= 1",
        ],
        "success_criteria": "revenue_lead_engine total_leads > 0",
        "troubleshooting": ["Lead gelmiyor → track endpoint + redirect URL kontrol"],
    },
}
