# -*- coding: utf-8 -*-
"""Kuşadası mahalle, cadde, sokak ve hizmet varyant verisi."""

from __future__ import annotations

# slug, görünen ad, cadde/sokak listesi (slug, ad, tip)
MAHALLELER: list[tuple[str, str, list[tuple[str, str, str]]]] = [
    ("kadinlar-denizi", "Kadınlar Denizi", [
        ("ataturk-caddesi", "Atatürk Caddesi", "cadde"),
        ("istiklal-caddesi", "İstiklal Caddesi", "cadde"),
        ("kahramanlar-caddesi", "Kahramanlar Caddesi", "cadde"),
        ("sirac-sokak", "Sıraç Sokak", "sokak"),
        ("turkmen-sokak", "Türkmen Sokak", "sokak"),
        ("guzelhisar-sokak", "Güzelhisar Sokak", "sokak"),
        ("deniz-sokak", "Deniz Sokak", "sokak"),
        ("sahil-sokak", "Sahil Sokak", "sokak"),
        ("meltem-sokak", "Meltem Sokak", "sokak"),
        ("pasa-limani-caddesi", "Paşa Limanı Caddesi", "cadde"),
        ("liman-caddesi", "Liman Caddesi", "cadde"),
        ("barbaros-caddesi", "Barbaros Hayrettin Paşa Caddesi", "cadde"),
    ]),
    ("yilanciburnu", "Yılancı Burnu", [
        ("yilanciburnu-caddesi", "Yılancı Burnu Caddesi", "cadde"),
        ("sahil-yolu", "Sahil Yolu", "cadde"),
        ("deniz-gulü-sokak", "Deniz Gülü Sokak", "sokak"),
        ("marti-sokak", "Martı Sokak", "sokak"),
        ("kumsal-sokak", "Kumsal Sokak", "sokak"),
        ("inci-sokak", "İnci Sokak", "sokak"),
        ("mercan-sokak", "Mercan Sokak", "sokak"),
        ("deniz-feneri-sokak", "Deniz Feneri Sokak", "sokak"),
    ]),
    ("guvercinada", "Güvercinada", [
        ("guvercinada-caddesi", "Güvercinada Caddesi", "cadde"),
        ("kale-sokak", "Kale Sokak", "sokak"),
        ("ada-sokak", "Ada Sokak", "sokak"),
        ("kordon-caddesi", "Kordon Caddesi", "cadde"),
        ("liman-sokak", "Liman Sokak", "sokak"),
        ("kalekapisi-sokak", "Kale Kapısı Sokak", "sokak"),
        ("fener-sokak", "Fener Sokak", "sokak"),
    ]),
    ("davutlar", "Davutlar", [
        ("davutlar-caddesi", "Davutlar Caddesi", "cadde"),
        ("davutlar-sahil-caddesi", "Davutlar Sahil Caddesi", "cadde"),
        ("gunes-sokak", "Güneş Sokak", "sokak"),
        ("yaz-sokak", "Yaz Sokak", "sokak"),
        ("palmiye-sokak", "Palmiye Sokak", "sokak"),
        ("deniz-yildizi-sokak", "Deniz Yıldızı Sokak", "sokak"),
        ("kumsal-caddesi", "Kumsal Caddesi", "cadde"),
        ("turkuaz-sokak", "Turkuaz Sokak", "sokak"),
    ]),
    ("kusadasi-merkez", "Kuşadası Merkez", [
        ("ataturk-caddesi", "Atatürk Caddesi", "cadde"),
        ("istiklal-caddesi", "İstiklal Caddesi", "cadde"),
        ("cumhuriyet-caddesi", "Cumhuriyet Caddesi", "cadde"),
        ("caferli-caddesi", "Caferli Caddesi", "cadde"),
        ("kahramanlar-caddesi", "Kahramanlar Caddesi", "cadde"),
        ("namik-kemal-caddesi", "Namık Kemal Caddesi", "cadde"),
        ("inonu-caddesi", "İnönü Caddesi", "cadde"),
        ("milli-egemenlik-caddesi", "Milli Egemenlik Caddesi", "cadde"),
        ("gaziosmanpasa-bulvari", "Gaziosmanpaşa Bulvarı", "bulvar"),
        ("turgut-ozal-bulvari", "Turgut Özal Bulvarı", "bulvar"),
        ("aydin-bulvari", "Aydın Bulvarı", "bulvar"),
        ("marina-caddesi", "Marina Caddesi", "cadde"),
        ("liman-caddesi", "Liman Caddesi", "cadde"),
        ("barbaros-caddesi", "Barbaros Caddesi", "cadde"),
        ("turkmen-caddesi", "Türkmen Caddesi", "cadde"),
    ]),
    ("turkmen", "Türkmen", [
        ("turkmen-caddesi", "Türkmen Caddesi", "cadde"),
        ("turkmen-sokak", "Türkmen Sokak", "sokak"),
        ("cinar-sokak", "Çınar Sokak", "sokak"),
        ("baglar-sokak", "Bağlar Sokak", "sokak"),
        ("yeni-sokak", "Yeni Sokak", "sokak"),
        ("gul-sokak", "Gül Sokak", "sokak"),
        ("pinar-sokak", "Pınar Sokak", "sokak"),
        ("bahce-sokak", "Bahçe Sokak", "sokak"),
    ]),
    ("cumhuriyet", "Cumhuriyet", [
        ("cumhuriyet-caddesi", "Cumhuriyet Caddesi", "cadde"),
        ("cumhuriyet-meydani", "Cumhuriyet Meydanı", "meydan"),
        ("istiklal-caddesi", "İstiklal Caddesi", "cadde"),
        ("ataturk-caddesi", "Atatürk Caddesi", "cadde"),
        ("caferli-caddesi", "Caferli Caddesi", "cadde"),
        ("kahramanlar-caddesi", "Kahramanlar Caddesi", "cadde"),
        ("gaziosmanpasa-bulvari", "Gaziosmanpaşa Bulvarı", "bulvar"),
        ("marina-caddesi", "Marina Caddesi", "cadde"),
    ]),
    ("hacifeyzullah", "Hacıfeyzullah", [
        ("hacifeyzullah-caddesi", "Hacıfeyzullah Caddesi", "cadde"),
        ("haci-sokak", "Hacı Sokak", "sokak"),
        ("feyzullah-sokak", "Feyzullah Sokak", "sokak"),
        ("camii-sokak", "Camii Sokak", "sokak"),
        ("pazar-sokak", "Pazar Sokak", "sokak"),
        ("cinar-sokak", "Çınar Sokak", "sokak"),
        ("yeni-mahalle-sokak", "Yeni Mahalle Sokak", "sokak"),
        ("baglar-sokak", "Bağlar Sokak", "sokak"),
    ]),
    ("camiatik", "Camiatik", [
        ("camiatik-caddesi", "Camiatik Caddesi", "cadde"),
        ("camiatik-sokak", "Camiatik Sokak", "sokak"),
        ("pazar-yeri-sokak", "Pazar Yeri Sokak", "sokak"),
        ("carsi-sokak", "Çarşı Sokak", "sokak"),
        ("han-sokak", "Han Sokak", "sokak"),
        ("bedesten-sokak", "Bedesten Sokak", "sokak"),
        ("esnaf-sokak", "Esnaf Sokak", "sokak"),
    ]),
    ("karaova", "Karaova", [
        ("karaova-caddesi", "Karaova Caddesi", "cadde"),
        ("karaova-sokak", "Karaova Sokak", "sokak"),
        ("baglar-caddesi", "Bağlar Caddesi", "cadde"),
        ("zeytinlik-sokak", "Zeytinlik Sokak", "sokak"),
        ("cinar-sokak", "Çınar Sokak", "sokak"),
        ("yayla-sokak", "Yayla Sokak", "sokak"),
        ("tepe-sokak", "Tepe Sokak", "sokak"),
    ]),
    ("sogucak", "Soğucak", [
        ("sogucak-caddesi", "Soğucak Caddesi", "cadde"),
        ("sogucak-sokak", "Soğucak Sokak", "sokak"),
        ("pinar-sokak", "Pınar Sokak", "sokak"),
        ("cinar-sokak", "Çınar Sokak", "sokak"),
        ("bahce-sokak", "Bahçe Sokak", "sokak"),
        ("gul-sokak", "Gül Sokak", "sokak"),
        ("yeni-sokak", "Yeni Sokak", "sokak"),
    ]),
    ("camlik", "Çamlık", [
        ("camlik-caddesi", "Çamlık Caddesi", "cadde"),
        ("camlik-sokak", "Çamlık Sokak", "sokak"),
        ("orman-sokak", "Orman Sokak", "sokak"),
        ("pinar-sokak", "Pınar Sokak", "sokak"),
        ("yayla-sokak", "Yayla Sokak", "sokak"),
        ("tepe-sokak", "Tepe Sokak", "sokak"),
        ("cinar-sokak", "Çınar Sokak", "sokak"),
    ]),
    ("yavansu", "Yavansu", [
        ("yavansu-caddesi", "Yavansu Caddesi", "cadde"),
        ("yavansu-sokak", "Yavansu Sokak", "sokak"),
        ("sahil-caddesi", "Sahil Caddesi", "cadde"),
        ("deniz-sokak", "Deniz Sokak", "sokak"),
        ("koy-sokak", "Koy Sokak", "sokak"),
        ("liman-sokak", "Liman Sokak", "sokak"),
        ("marina-sokak", "Marina Sokak", "sokak"),
    ]),
    ("degirmendere", "Değirmendere", [
        ("degirmendere-caddesi", "Değirmendere Caddesi", "cadde"),
        ("degirmendere-sokak", "Değirmendere Sokak", "sokak"),
        ("dere-sokak", "Dere Sokak", "sokak"),
        ("pinar-sokak", "Pınar Sokak", "sokak"),
        ("cinar-sokak", "Çınar Sokak", "sokak"),
        ("bahce-sokak", "Bahçe Sokak", "sokak"),
        ("yayla-sokak", "Yayla Sokak", "sokak"),
    ]),
    ("guzelcamli", "Güzelçamlı", [
        ("guzelcamli-caddesi", "Güzelçamlı Caddesi", "cadde"),
        ("sahil-caddesi", "Sahil Caddesi", "cadde"),
        ("ataturk-caddesi", "Atatürk Caddesi", "cadde"),
        ("cumhuriyet-caddesi", "Cumhuriyet Caddesi", "cadde"),
        ("deniz-sokak", "Deniz Sokak", "sokak"),
        ("kumsal-sokak", "Kumsal Sokak", "sokak"),
        ("palmiye-sokak", "Palmiye Sokak", "sokak"),
        ("gunes-sokak", "Güneş Sokak", "sokak"),
        ("marti-sokak", "Martı Sokak", "sokak"),
    ]),
    ("kirazli", "Kirazlı", [
        ("kirazli-caddesi", "Kirazlı Caddesi", "cadde"),
        ("kirazli-sokak", "Kirazlı Sokak", "sokak"),
        ("baglar-sokak", "Bağlar Sokak", "sokak"),
        ("cinar-sokak", "Çınar Sokak", "sokak"),
        ("tepe-sokak", "Tepe Sokak", "sokak"),
        ("yayla-sokak", "Yayla Sokak", "sokak"),
    ]),
    ("yaylakoy", "Yaylaköy", [
        ("yaylakoy-caddesi", "Yaylaköy Caddesi", "cadde"),
        ("yayla-sokak", "Yayla Sokak", "sokak"),
        ("tepe-sokak", "Tepe Sokak", "sokak"),
        ("baglar-sokak", "Bağlar Sokak", "sokak"),
        ("cinar-sokak", "Çınar Sokak", "sokak"),
        ("pinar-sokak", "Pınar Sokak", "sokak"),
    ]),
    ("efes", "Efes", [
        ("efes-caddesi", "Efes Caddesi", "cadde"),
        ("antik-sokak", "Antik Sokak", "sokak"),
        ("tarih-sokak", "Tarih Sokak", "sokak"),
        ("turizm-sokak", "Turizm Sokak", "sokak"),
        ("otogar-caddesi", "Otogar Caddesi", "cadde"),
        ("ephesus-bulvari", "Ephesus Bulvarı", "bulvar"),
    ]),
    ("ovakent", "Ovakent", [
        ("ovakent-caddesi", "Ovakent Caddesi", "cadde"),
        ("ovakent-sokak", "Ovakent Sokak", "sokak"),
        ("yeni-sokak", "Yeni Sokak", "sokak"),
        ("bahce-sokak", "Bahçe Sokak", "sokak"),
        ("cinar-sokak", "Çınar Sokak", "sokak"),
    ]),
    ("agacli", "Ağaçlı", [
        ("agacli-caddesi", "Ağaçlı Caddesi", "cadde"),
        ("agacli-sokak", "Ağaçlı Sokak", "sokak"),
        ("orman-sokak", "Orman Sokak", "sokak"),
        ("pinar-sokak", "Pınar Sokak", "sokak"),
        ("tepe-sokak", "Tepe Sokak", "sokak"),
    ]),
    ("ozbey", "Özbey", [
        ("ozbey-caddesi", "Özbey Caddesi", "cadde"),
        ("ozbey-sokak", "Özbey Sokak", "sokak"),
        ("baglar-sokak", "Bağlar Sokak", "sokak"),
        ("yayla-sokak", "Yayla Sokak", "sokak"),
        ("cinar-sokak", "Çınar Sokak", "sokak"),
    ]),
    ("marina", "Marina", [
        ("marina-caddesi", "Marina Caddesi", "cadde"),
        ("yat-limani-caddesi", "Yat Limanı Caddesi", "cadde"),
        ("iskele-sokak", "İskele Sokak", "sokak"),
        ("rıhtım-sokak", "Rıhtım Sokak", "sokak"),
        ("deniz-sokak", "Deniz Sokak", "sokak"),
        ("pier-sokak", "Pier Sokak", "sokak"),
        ("liman-sokak", "Liman Sokak", "sokak"),
    ]),
    ("zeus", "Zeus", [
        ("zeus-caddesi", "Zeus Caddesi", "cadde"),
        ("oteller-sokagi", "Oteller Sokağı", "sokak"),
        ("turizm-sokak", "Turizm Sokak", "sokak"),
        ("plaj-yolu", "Plaj Yolu", "cadde"),
        ("sahil-sokak", "Sahil Sokak", "sokak"),
    ]),
]

# Hizmet / uyruk / yetişkin varyantları (slug, kısa ad)
VARIANTS: list[tuple[str, str]] = [
    ("turk-escort", "Türk Escort"),
    ("rus-escort", "Rus Escort"),
    ("ukraynali-escort", "Ukraynalı Escort"),
    ("moldovali-escort", "Moldovalı Escort"),
    ("yabanci-escort", "Yabancı Escort"),
    ("beyaz-rus-escort", "Beyaz Rus Escort"),
    ("gurcu-escort", "Gürcü Escort"),
    ("romen-escort", "Romen Escort"),
    ("bulgar-escort", "Bulgar Escort"),
    ("kazak-escort", "Kazak Escort"),
    ("vip-escort", "VIP Escort"),
    ("premium-escort", "Premium Escort"),
    ("luks-escort", "Lüks Escort"),
    ("elite-escort", "Elite Escort"),
    ("ucuz-escort", "Ucuz Escort"),
    ("anal-escort", "Anal Escort"),
    ("oral-escort", "Oral Escort"),
    ("cim-escort", "CIM Escort"),
    ("cif-escort", "CIF Escort"),
    ("cim-cif-escort", "CIM CIF Escort"),
    ("yutmali-escort", "Yutmalı Escort"),
    ("deepthroat-escort", "Deepthroat Escort"),
    ("rimming-escort", "Rimming Escort"),
    ("french-kiss-escort", "French Kiss Escort"),
    ("69-escort", "69 Escort"),
    ("masaj-escort", "Masaj Escort"),
    ("erotik-masaj-escort", "Erotik Masaj Escort"),
    ("nuru-masaj-escort", "Nuru Masaj Escort"),
    ("happy-ending-escort", "Happy Ending Escort"),
    ("striptiz-escort", "Striptiz Escort"),
    ("fantezi-escort", "Fantezi Escort"),
    ("roleplay-escort", "Roleplay Escort"),
    ("bdsm-escort", "BDSM Escort"),
    ("domina-escort", "Domina Escort"),
    ("lezbiyen-show-escort", "Lezbiyen Show Escort"),
    ("cift-escort", "Çift Escort"),
    ("grup-escort", "Grup Escort"),
    ("uclu-escort", "Üçlü Escort"),
    ("dortlu-escort", "Dörtlü Escort"),
    ("escort-cifti", "Escort Çifti"),
    ("gfe-escort", "GFE Escort"),
    ("porno-star-escort", "Porno Star Escort"),
    ("universiteli-escort", "Üniversiteli Escort"),
    ("genc-escort", "Genç Escort"),
    ("yetiskin-escort", "Yetişkin Escort"),
    ("olgun-escort", "Olgun Escort"),
    ("milf-escort", "MILF Escort"),
    ("orta-yas-escort", "Orta Yaş Escort"),
    ("sarisin-escort", "Sarışın Escort"),
    ("esmer-escort", "Esmer Escort"),
    ("kizil-escort", "Kızıl Escort"),
    ("kumral-escort", "Kumral Escort"),
    ("balik-etli-escort", "Balık Etli Escort"),
    ("fit-escort", "Fit Escort"),
    ("minyon-escort", "Minyon Escort"),
    ("uzun-boylu-escort", "Uzun Boylu Escort"),
    ("dolgun-escort", "Dolgun Escort"),
    ("zayif-escort", "Zayıf Escort"),
    ("eve-gelen-escort", "Eve Gelen Escort"),
    ("otele-gelen-escort", "Otele Gelen Escort"),
    ("otel-escort", "Otel Escort"),
    ("plaj-escort", "Plaj Escort"),
    ("gece-escort", "Gece Escort"),
    ("24saat-escort", "24 Saat Escort"),
    ("jakuzili-escort", "Jakuzili Escort"),
    ("fetish-escort", "Fetish Escort"),
    ("ayak-fetis-escort", "Ayak Fetiş Escort"),
    ("strapon-escort", "Strapon Escort"),
    ("sahibe-escort", "Sahibe Escort"),
    ("seker-escort", "Şeker Escort"),
    ("ingilizce-escort", "İngilizce Escort"),
    ("rusca-escort", "Rusça Escort"),
    ("almanca-escort", "Almanca Escort"),
    ("arapca-escort", "Arapça Escort"),
    ("fransizca-escort", "Fransızca Escort"),
]

GEO_FACTS = {
    "kadinlar-denizi": "Kadınlar Denizi, Kuşadası'nın en bilinen plaj ve eğlence aksıdır; sahil şeridi, oteller ve gece hayatı yoğundur.",
    "yilanciburnu": "Yılancı Burnu, Kadınlar Denizi'ne yakın konumuyla yaz sezonunda yoğun ziyaretçi alan sahil mahallesidir.",
    "guvercinada": "Güvercinada, kale ve tarihi doku ile Kuşadası limanına hakim özel bir yarımadadır.",
    "davutlar": "Davutlar, Kuşadası'nın güneybatısında geniş sahil şeridi ve tatil köyleriyle bilinir.",
    "kusadasi-merkez": "Kuşadası Merkez, çarşı, marina ve ana caddelerin kesiştiği ticari kalbidir.",
    "turkmen": "Türkmen mahallesi, merkeze yürüme mesafesinde konut ve butik otel bölgesidir.",
    "cumhuriyet": "Cumhuriyet, Kuşadası'nın ana meydan ve alışveriş aksına ev sahipliği yapar.",
    "hacifeyzullah": "Hacıfeyzullah, yerleşik nüfusun yoğun olduğu merkezi mahallelerden biridir.",
    "camiatik": "Camiatik, geleneksel çarşı dokusu ve esnaf sokaklarıyla tanınır.",
    "karaova": "Karaova, merkeze bağlı yamaç ve bağlar bölgesi mahallesidir.",
    "sogucak": "Soğucak, sakin sokak yapısıyla yerel yaşamın hissedildiği mahalledir.",
    "camlik": "Çamlık, yeşil alanlara yakın konumuyla aile mahalleleri arasında sayılır.",
    "yavansu": "Yavansu, marina ve koylara yakın sahil mahallesidir.",
    "degirmendere": "Değirmendere, dere kenarı ve yerleşik konut dokusuyla bilinir.",
    "guzelcamli": "Güzelçamlı, Kuşadası'na bağlı sahil beldesi; Dilek Yarımadası'na yakındır.",
    "kirazli": "Kirazlı, merkez Kuşadası'na bağlı kırsal-kentsel geçiş mahallesidir.",
    "yaylakoy": "Yaylaköy, yüksek konumuyla manzara ve sakin sokaklarıyla öne çıkar.",
    "efes": "Efes bölgesi, antik kent turizmi ve otogar aksına yakın konumdadır.",
    "ovakent": "Ovakent, genişleme alanı ve yeni yapılaşmanın olduğu mahalledir.",
    "agacli": "Ağaçlı, merkeze bağlı yeşil çevreli yerleşim mahallesidir.",
    "ozbey": "Özbey, Kuşadası merkezine bağlı konut mahallesidir.",
    "marina": "Marina, yat limanı, iskele ve sahil restoranlarının yoğunlaştığı bölgedir.",
    "zeus": "Zeus bölgesi, otel kuşağı ve plaj yolu ile turistik konaklama aksıdır.",
}

LANDMARKS = [
    "Kuşadası Limanı", "Marina İskelesi", "Güvercinada Kalesi", "Kadınlar Denizi Plajı",
    "Davutlar Sahili", "Öküz Mehmet Paşa Kervansarayı", "Kuşadası Çarşı", "Dilek Yarımadası girişi",
    "Efes Antik Kenti yolu", "Kuşadası Otogar", "Turgut Özal Bulvarı", "Atatürk Caddesi",
]
