# -*- coding: utf-8 -*-
"""Pornhub tarzı kategori listesi — EN + TR ayrı slug/isim."""

from __future__ import annotations

# (en_slug, en_name, tr_slug, tr_name)
CATEGORIES: list[tuple[str, str, str, str]] = [
    ("ebony", "Ebony", "siyahi", "Siyahi"),
    ("bbw", "BBW", "balik-etli", "Balık Etli"),
    ("solo-female", "Solo Female", "solo-bayan", "Solo Bayan"),
    ("big-dick", "Big Dick", "buyuk-penis", "Büyük Penis"),
    ("masturbation", "Masturbation", "masturbasyon", "Mastürbasyon"),
    ("transgender", "Transgender", "trans", "Trans"),
    ("pornstar", "Pornstar", "porno-star", "Porno Star"),
    ("exclusive", "Exclusive", "ekskluizif", "Eksklüzif"),
    ("interracial", "Interracial", "irklar-arasi", "Irklar Arası"),
    ("small-tits", "Small Tits", "kucuk-gogus", "Küçük Göğüs"),
    ("18-25", "18-25", "18-25-yas", "18-25 Yaş"),
    ("60fps", "60FPS", "60fps", "60FPS"),
    ("ai", "AI", "yapay-zeka", "Yapay Zeka"),
    ("amateur", "Amateur", "amatör", "Amatör"),
    ("anal", "Anal", "anal", "Anal"),
    ("arab", "Arab", "arap", "Arap"),
    ("asian", "Asian", "asyali", "Asyalı"),
    ("babe", "Babe", "atesli-bayan", "Ateşli Bayan"),
    ("babysitter", "Babysitter (18+)", "dadı-18", "Dadı (18+)"),
    ("behind-the-scenes", "Behind The Scenes", "kamera-arkasi", "Kamera Arkası"),
    ("big-ass", "Big Ass", "buyuk-kalca", "Büyük Kalça"),
    ("big-tits", "Big Tits", "buyuk-gogus", "Büyük Göğüs"),
    ("bisexual-male", "Bisexual Male", "biseksuel-erkek", "Biseksüel Erkek"),
    ("blonde", "Blonde", "sarisin", "Sarışın"),
    ("blowjob", "Blowjob", "oral-seks", "Oral Seks"),
    ("bondage", "Bondage", "baglama", "Bağlama"),
    ("brazilian", "Brazilian", "brezilyali", "Brezilyalı"),
    ("british", "British", "ingiliz", "İngiliz"),
    ("brunette", "Brunette", "kumral", "Kumral"),
    ("bukkake", "Bukkake", "bukkake", "Bukkake"),
    ("cartoon", "Cartoon", "cizgi-film", "Çizgi Film"),
    ("casting", "Casting", "casting", "Casting"),
    ("celebrity", "Celebrity", "unlu", "Ünlü"),
    ("closed-captions", "Closed Captions", "altyazi", "Altyazı"),
    ("college", "College (18+)", "universite-18", "Üniversite (18+)"),
    ("compilation", "Compilation", "derleme", "Derleme"),
    ("cosplay", "Cosplay", "cosplay", "Cosplay"),
    ("creampie", "Creampie", "icine-bosalma", "İçine Boşalma"),
    ("cuckold", "Cuckold", "cuckold", "Cuckold"),
    ("cumshot", "Cumshot", "bosalma", "Boşalma"),
    ("czech", "Czech", "cek", "Çek"),
    ("deepthroat", "Deepthroat", "derin-bogaz", "Derin Boğaz"),
    ("described-video", "Described Video", "betimlemeli-video", "Betimlemeli Video"),
    ("double-penetration", "Double Penetration", "cift-penetrasyon", "Çift Penetrasyon"),
    ("euro", "Euro", "avrupa", "Avrupa"),
    ("feet", "Feet", "ayak-fetis", "Ayak Fetiş"),
    ("female-orgasm", "Female Orgasm", "bayan-orgazm", "Bayan Orgazm"),
    ("fetish", "Fetish", "fetis", "Fetiş"),
    ("fingering", "Fingering", "parmaklama", "Parmaklama"),
    ("fisting", "Fisting", "fisting", "Fisting"),
    ("french", "French", "fransiz", "Fransız"),
    ("funny", "Funny", "komik", "Komik"),
    ("gaming", "Gaming", "oyun", "Oyun"),
    ("gangbang", "Gangbang", "gangbang", "Gangbang"),
    ("german", "German", "alman", "Alman"),
    ("handjob", "Handjob", "el-ile", "El İle"),
    ("hardcore", "Hardcore", "hardcore", "Hardcore"),
    ("hd-porn", "HD Porn", "hd-porno", "HD Porno"),
    ("hentai", "Hentai", "hentai", "Hentai"),
    ("indian", "Indian", "hintli", "Hintli"),
    ("interactive", "Interactive", "interaktif", "İnteraktif"),
    ("italian", "Italian", "italyan", "İtalyan"),
    ("japanese", "Japanese", "japon", "Japon"),
    ("korean", "Korean", "koreli", "Koreli"),
    ("latina", "Latina", "latin", "Latin"),
    ("lesbian", "Lesbian", "lezbiyen", "Lezbiyen"),
    ("massage", "Massage", "masaj", "Masaj"),
    ("mature", "Mature", "olgun", "Olgun"),
    ("milf", "MILF", "milf", "MILF"),
    ("muscular-men", "Muscular Men", "kasli-erkek", "Kaslı Erkek"),
    ("music", "Music", "muzik", "Müzik"),
    ("old-young", "Old/Young (18+)", "olgun-genc-18", "Olgun Genç (18+)"),
    ("orgy", "Orgy", "orgi", "Orgi"),
    ("parody", "Parody", "parodi", "Parodi"),
    ("party", "Party", "parti", "Parti"),
    ("pissing", "Pissing", "idrar", "İdrar"),
    ("podcast", "Podcast", "podcast", "Podcast"),
    ("popular-with-women", "Popular With Women", "kadinlara-populer", "Kadınlara Popüler"),
    ("pov", "POV", "pov", "POV"),
    ("public", "Public", "halka-acik", "Halka Açık"),
    ("pussy-licking", "Pussy Licking", "suni-emme", "Am Yalama"),
    ("reaction", "Reaction", "reaksiyon", "Reaksiyon"),
    ("reality", "Reality", "gerceklik", "Gerçeklik"),
    ("red-head", "Red Head", "kizil", "Kızıl"),
    ("role-play", "Role Play", "rol-oyunu", "Rol Oyunu"),
    ("romantic", "Romantic", "romantik", "Romantik"),
    ("rough-sex", "Rough Sex", "sert-seks", "Sert Seks"),
    ("russian", "Russian", "rus", "Rus"),
    ("school", "School (18+)", "okul-18", "Okul (18+)"),
    ("sfw", "SFW", "sfw", "SFW"),
    ("smoking", "Smoking", "sigara", "Sigara"),
    ("solo-male", "Solo Male", "solo-erkek", "Solo Erkek"),
    ("squirt", "Squirt", "squirt", "Squirt"),
    ("step-fantasy", "Step Fantasy", "uvey-fantezi", "Üvey Fantezi"),
    ("strap-on", "Strap On", "strapon", "Strapon"),
    ("striptease", "Striptease", "striptiz", "Striptiz"),
    ("tattooed-women", "Tattooed Women", "dovmeli-bayan", "Dövmeli Bayan"),
    ("threesome", "Threesome", "uclu", "Üçlü"),
    ("toys", "Toys", "oyuncak", "Oyuncak"),
    ("verified-amateurs", "Verified Amateurs", "dogrulanmis-amator", "Doğrulanmış Amatör"),
    ("verified-couples", "Verified Couples", "dogrulanmis-cift", "Doğrulanmış Çift"),
    ("verified-models", "Verified Models", "dogrulanmis-model", "Doğrulanmış Model"),
    ("vintage", "Vintage", "vintage", "Vintage"),
    ("virtual-reality", "Virtual Reality", "sanal-gerceklik", "Sanal Gerçeklik"),
    ("webcam", "Webcam", "webcam", "Webcam"),
]
